server:
  port: 8087

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/hrm-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

keycloak:
  auth-server-url: http://localhost:9090
  realm: hrm-realm

  # CLIENT LOGIN
  login-client-id: hrm-client
  login-client-secret: agqLg7QgphMWFDLeye4sh1S6Y574cAvZ

  # CLIENT ADMIN
  admin-client-id: auth-service-client
  admin-client-secret: ignWKHc8samEOEAwy4dlvmedab4RZLxt

  token-url: http://localhost:9090/realms/hrm-realm/protocol/openid-connect/token
  logout-url: http://localhost:9090/realms/hrm-realm/protocol/openid-connect/logout
  admin-create-user-url: http://localhost:9090/admin/realms/hrm-realm/users
  admin-base-url: http://localhost:9090/admin/realms/hrm-realm